name: test
on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: .npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5
        with:
          push: never
          runCmd: |
            npm test
            npm run prod
