name: update devcontainer image
on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - docker-compose*.yml
      - .devcontainer/**/*

jobs:
  build:
    uses: sarisia/workflows/.github/workflows/update-devcontainer.yml@6f14ef8702cf81d8ebac0308c713a8dca5558586
    permissions:
      contents: read
      packages: write
