name: update devcontainer image
on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - docker-compose*.yml
      - .devcontainer/**/*

jobs:
  build:
    uses: sarisia/workflows/.github/workflows/update-devcontainer.yml@257926c94a642619ae8ff0debfb5411db2c80a7f
    permissions:
      contents: read
      packages: write
